<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MarkdownDotNetRenderer.Cli</RootNamespace>
    <AssemblyName>mdrender</AssemblyName>
    <PublishAot>true</PublishAot>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarkdownDotNetRenderer.Core\MarkdownDotNetRenderer.Core.csproj" />
  </ItemGroup>

</Project>
