<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MarkdownDotNetRenderer</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="1.3.2" />
  </ItemGroup>

</Project>
